# Generated by Django 3.2.9 on 2021-12-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211223_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
    ]
