# Generated by Django 3.2.9 on 2021-12-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fall_winter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='spring_summer',
            field=models.BooleanField(default=False),
        ),
    ]
