# Generated by Django 3.2.9 on 2021-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='callBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_call', models.CharField(max_length=100, verbose_name='name_call')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('email_call', models.CharField(max_length=100, verbose_name='email_call')),
                ('message', models.CharField(max_length=150, verbose_name='message')),
            ],
        ),
    ]
